services:
  postgres:
    image: postgres:15
    container_name: myleads-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leads
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
